In [8]:
import csv

def import_csv(csvfile):
    """
    Imports the CSV file as an array of lines
    
    :param csvfile: The path of the CSV file
    :return lines: The lines of the CSV file 
    """
    lines = []
    with open(log_path) as csvfile:
        reader = csv.reader(csvfile)
        for line in reader:
            lines.append(line)

    lines.pop(0) # Remove the header info from the CSV file
    return lines

In [9]:
data_path = './data/'
img_path = data_path + 'IMG/'
log_path = data_path + 'driving_log.csv'

# Store the lines of the CSV file in an array
lines = []
lines = import_csv(log_path)

In [10]:
# Test to make sure we read that properly
print(lines[0])

['/Users/greg/Documents/Udacity/CarND/term1/CarND-Behavioral-Cloning-P3/data/IMG/center_2017_05_28_10_49_49_163.jpg', '/Users/greg/Documents/Udacity/CarND/term1/CarND-Behavioral-Cloning-P3/data/IMG/left_2017_05_28_10_49_49_163.jpg', '/Users/greg/Documents/Udacity/CarND/term1/CarND-Behavioral-Cloning-P3/data/IMG/right_2017_05_28_10_49_49_163.jpg', '-0.04981203', '0', '0', '5.219624']


In [11]:
# Transform to a relative path to the images
for line in lines:
    line[0] = line[0].split('/')[-1]
    line[1] = line[1].split('/')[-1]
    line[2] = line[2].split('/')[-1]
    
# Test
print(lines[0])

['center_2017_05_28_10_49_49_163.jpg', 'left_2017_05_28_10_49_49_163.jpg', 'right_2017_05_28_10_49_49_163.jpg', '-0.04981203', '0', '0', '5.219624']


In [12]:
import cv2
import numpy as np

left_images = []
center_images = []
right_images = []
meas = []

# Make lines a numpy array
lines = np.array(lines)

# Import the images and the corresponding steering measurements
center_images = lines[:,0]
left_images = lines[:,1]
right_images = lines[:,2]
steer_meas = lines[:,3]

# Test to make sure we got that right
print(left_images[0:5])
print(center_images[0:5])
print(right_images[0:5])
print(steer_meas[0:5])

print(len(left_images))
print(len(center_images))
print(len(right_images))
print(len(steer_meas))

['left_2017_05_28_10_49_49_163.jpg' 'left_2017_05_28_10_49_49_231.jpg'
 'left_2017_05_28_10_49_49_309.jpg' 'left_2017_05_28_10_49_49_382.jpg'
 'left_2017_05_28_10_49_49_460.jpg']
['center_2017_05_28_10_49_49_163.jpg' 'center_2017_05_28_10_49_49_231.jpg'
 'center_2017_05_28_10_49_49_309.jpg' 'center_2017_05_28_10_49_49_382.jpg'
 'center_2017_05_28_10_49_49_460.jpg']
['right_2017_05_28_10_49_49_163.jpg' 'right_2017_05_28_10_49_49_231.jpg'
 'right_2017_05_28_10_49_49_309.jpg' 'right_2017_05_28_10_49_49_382.jpg'
 'right_2017_05_28_10_49_49_460.jpg']
['-0.04981203' '-0.04981203' '-0.04981203' '-0.04981203' '-0.04981203']
45714
45714
45714
45714


In [13]:
# Transform the measurements array to float
steer_meas = steer_meas.astype(np.float32)

# Test the new data type
print(steer_meas[0:5])

[-0.04981203 -0.04981203 -0.04981203 -0.04981203 -0.04981203]


In [14]:
# Apply an offset to left and right steering angles
offset = 1.0
dist = 20.0

steer_offset = offset / dist * 360/(2*np.pi) / 25.0\

left_steer_meas = steer_meas + steer_offset
right_steer_meas = steer_meas - steer_offset

# Test the steering offset
print(left_steer_meas[0:5])
print(right_steer_meas[0:5])

[ 0.06477953  0.06477953  0.06477953  0.06477953  0.06477953]
[-0.16440359 -0.16440359 -0.16440359 -0.16440359 -0.16440359]


In [15]:
# Put the paths for left, right, and center images into one dataset
samples = []
samples.extend(center_images)
samples.extend(left_images)
samples.extend(right_images)

# Test that
print(len(samples))
print(samples[0], samples[46000], samples[95000])

137142
center_2017_05_28_10_49_49_163.jpg left_2017_05_28_10_50_10_314.jpg right_2017_05_28_10_56_42_360.jpg


In [16]:
# Put the angles for left, right, and center images into one dataset
meas = []
meas.extend(steer_meas)
meas.extend(left_steer_meas)
meas.extend(right_steer_meas)

# Test that
print(len(meas))
print(meas[0], meas[46000], meas[95000])

137142
-0.049812 0.0510049 -0.138279


In [17]:
from sklearn.utils import shuffle

# Shuffle the datasets in unison
samples, meas = shuffle(samples, meas)

# Test the output
print(samples[0:10])
print(meas[0:10])

['left_2017_05_28_10_53_27_036.jpg', 'center_2017_05_28_11_27_18_966.jpg', 'left_2017_05_28_10_58_11_179.jpg', 'left_2017_05_28_12_14_44_447.jpg', 'right_2017_05_28_11_46_28_284.jpg', 'center_2017_05_28_12_34_55_800.jpg', 'right_2016_12_01_13_33_26_761.jpg', 'left_2017_05_28_12_20_16_305.jpg', 'left_2017_05_28_11_12_33_451.jpg', 'left_2017_05_28_10_49_59_990.jpg']
[0.072503924, -0.20054039, 0.020254165, 0.1298935, -0.18132088, -0.01193903, -0.11459156, 0.19173265, 0.10949581, 0.03822878]


In [18]:
from sklearn.model_selection import train_test_split

# Separate the data into training and validation sets
# Note: samples=X_, meas=y_
X_train, X_valid, y_train, y_valid = train_test_split(samples, meas, test_size=0.25, random_state=42)

# Make sure we did that properly
print(X_train[0:5])
print(y_train[0:5])
print(X_valid[0:5])
print(y_valid[0:5])

['center_2016_12_01_13_33_47_670.jpg', 'left_2017_05_28_12_25_11_807.jpg', 'center_2017_05_28_10_50_44_357.jpg', 'left_2017_05_28_12_44_22_530.jpg', 'right_2016_12_01_13_38_30_039.jpg']
[0.0, 0.21427436, -0.01678513, -0.12834483, -0.11459156]
['right_2017_05_28_11_45_46_567.jpg', 'center_2017_05_28_12_24_39_321.jpg', 'left_2017_05_28_11_51_40_236.jpg', 'right_2017_05_28_12_20_10_674.jpg', 'left_2017_05_28_11_12_25_519.jpg']
[-0.15855891, 0.01013275, 0.089142188, -0.062400542, 0.07416334]


In [19]:
# Define the shape of the trimmed image to run the model on
ch, rw, col = 160, 320, 3

In [20]:
from keras.models import Sequential, Model
from keras.layers import Flatten, Dense, Lambda, Cropping2D
from keras.layers.convolutional import Convolution2D
from keras.layers.pooling import MaxPooling2D
from keras.layers.core import Dropout

def nvidia_model(): 
    """
    NVIDIA model
    """
    model = Sequential()
    model.add(Cropping2D(cropping=((70, 25), (0, 0)),
                         input_shape=(ch, rw, col)))
    model.add(Lambda(lambda x: x / 255.0 - 0.5))
    model.add(Convolution2D(24, 5, 5, subsample=(2, 2), activation="relu"))
    model.add(Convolution2D(36, 5, 5, subsample=(2, 2), activation="relu"))
    model.add(Convolution2D(48, 5, 5, subsample=(2, 2), activation="relu"))
    model.add(Convolution2D(64, 3, 3, activation="relu"))
    model.add(Convolution2D(64, 3, 3, activation="relu"))
    model.add(Flatten())
    model.add(Dense(100))
    model.add(Dense(50))
    model.add(Dense(10))
    model.add(Dense(1))

    model.compile(loss='mse', optimizer='adam')
    return model

Using TensorFlow backend.


In [21]:
import cv2

def process_img(image):
    """
    Preprocessing for an image
    
    :param image: The image to be processed
    :return img: The processed image
    """
    # Convert to YUV color space
    img = cv2.cvtColor(image, cv2.COLOR_BGR2YUV)
    return img

def generator(samples, measurements, batch_size=32):
    """
    Generator to reduce memory footprint when training
    
    :param samples: The array of images to process
    :param measurements: The array of steering angle measurements
    :param batch_size: The number of samples to process concurrently
    :yield: The generator
    """
    assert len(samples) == len(measurements)
    num_samples = len(samples)

    while 1: # Loop forever so the generator never terminates
        for offset in range(0, num_samples, batch_size):
            batch_samples = samples[offset:offset+batch_size]
            batch_meas = measurements[offset:offset+batch_size]

            images = []
            angles = []
            for i, sample_val in enumerate(batch_samples):
                image = cv2.imread(img_path + sample_val, cv2.IMREAD_COLOR)
                angle = batch_meas[i]
                img = process_img(image)

                images.append(img)
                angles.append(angle)

            X_arr = np.array(images)
            y_arr = np.array(angles)
            yield shuffle(X_arr, y_arr)

In [22]:
import matplotlib.pyplot as plt

def plot_results(history):
    """
    Plot the results 
    
    :param history: The fit model
    """
    # Print the keys in the history object
    print(history.history.keys())

    # Plot training and validation loss
    plt.plot(history.history['loss'])
    plt.plot(history.history['val_loss'])
    plt.title('model mean squared error loss')
    plt.ylabel('mean squared error loss')
    plt.xlabel('epoch')
    plt.legend(['training set', 'validation set'], loc='upper right')
    plt.savefig("training_validation_loss_plot.jpg")
    plt.show()

In [ ]:
# Compile and train the model using the generator
batch_size = 128
num_epochs = 10

train_generator = generator(X_train, y_train, batch_size)
valid_generator = generator(X_valid, y_valid, batch_size)

model = nvidia_model()
model.save('model.h0')

fit_model = model.fit_generator(train_generator,
                                samples_per_epoch=3*len(X_train),
                                validation_data=valid_generator,
                                nb_val_samples=len(X_valid),
                                nb_epoch=num_epochs,
                                verbose=1)

plot_results(fit_model)

Epoch 1/10
308568/308568 [==============================] - 3086s - loss: 0.0066 - val_loss: 0.0052